const CartActionTypes = {
  CART_ADD_ITEM: 'CART_ADD_ITEM',
  CARD_REMOVE_ITEM: 'CARD_REMOVE_ITEM',
  CART_SAVE_PAYMENT_METHOD: 'CART_SAVE_PAYMENT_METHOD',
  CART_SAVE_SHIPPING_ADDRESS: 'CART_SAVE_SHIPPING_ADDRESS',
};
export default CartActionTypes;
